### ISSUE TITLE
Disabled prop for buttons

### ISSUE THREAD

**Issue by rudolfbruder** [wireui/wireui#11]
Hi,

I would like to dynamically set disabled prop on the x-button component however im unsuccessful. 

I did a bit of googling and i dont think you can set the disabled prop to true or false because it doesnt work on this basis.

` <x-button wire:click="selectImage" md icon="check" positive label="Positive"
                    disabled="{{$selectedImagePath ? false : true }}" />`

Could you help me out a bit please?

Thank you very much.

**Comment by ph7jack** [comment]
Hello @Greenvold 

The buttom component follow the native html button options
https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/button#attr-disabled

You must pass a boolean value in disabled prop, ex:
`<x-button wire:click="selectImage" md icon="check" positive label="Positive" :disabled="!$selectedImagePath" />`

Or

`<x-button wire:click="selectImage" md icon="check" positive label="Positive" :disabled="(bool) !$selectedImagePath" />`

------

```
<x-button wire:click="selectImage" md icon="check" positive label="Positive" disabled="{{$selectedImagePath ? false : true }}" />
```

This will render

```
<button ... disabled="1 or 0">Positive</button>
```

**Comment by rudolfbruder** [comment]
Thank you very much for your help. I was trying this approach but probably forgot : before the disabled prop.
