### ISSUE TITLE
Date picker min max

### ISSUE THREAD

**Issue by trippo** [wireui/wireui#14]
**Describe the solution you'd like**
Add the option to set min and max limit on datepicker like HTML input date 

https://www.w3schools.com/jsref/prop_date_min.asp

**Comment by ph7jack** [comment]
Great idea, I'll be working on this feature soon

**Comment by NickolasDzR** [comment]
@PH7-Jack Please, can you end this feature. 😊 I see that this is almost done

**Comment by ph7jack** [comment]
@NickolasDzR it is now finished. I was fixing the timezone issues

**Comment by ph7jack** [comment]
@trippo this feature is now finished, Thank you. Enjoy wireui
