### ISSUE TITLE
Button loading spinner

### ISSUE THREAD

**Issue by eppak** [wireui/wireui#17]
It would be nice to have a flag on the button that, if present, not only lock (as already do) the button but show a waiter icon like a spinner. What do you think?

**Comment by ph7jack** [comment]
Can you give one example? img, link...

**Comment by eppak** [comment]
I try to create a mockup and upload here, for the mechanism i thought that wire:loading fit the job. When pressed a fake button compare with a spinner until the end of the operation. For now can you tag this with feature request label? I'll update with the mockup soon.

**Comment by ph7jack** [comment]
Like this?
![image](https://user-images.githubusercontent.com/38913462/121537703-8799f700-c9da-11eb-97bf-e8c07a34c212.png)
When action x is fired, button show loading spinner

**Comment by eppak** [comment]
Yes, exactly!

**Comment by ph7jack** [comment]
It is now released 
https://livewire-wireui.com/docs/buttons#loading-spinner
