### ISSUE TITLE
Undefined variable $_instance

### ISSUE THREAD

**Issue by aliqasemzadeh** [wireui/wireui#20]
After I add currency input I get:
````
ErrorException
Undefined variable $_instance (View: C:\xampp\htdocs\noyan-io\resources\views\vendor\wireui\components\inputs\currency.blade.php)
````

currency input code:
````
                        <x-inputs.currency
                            label="Currency"
                            placeholder="Currency"
                            icon="currency-dollar"
                            thousands="."
                            decimal=","
                            precision="4"
                            wire:model="currency"
                        />
````

**Comment by ph7jack** [comment]
Is this component inside a livewire component?

**Comment by aliqasemzadeh** [comment]
No
It is not in livewire.

**Comment by ph7jack** [comment]
This component needs a livewire instance to work, because are using **@entangle** directive

**Comment by aliqasemzadeh** [comment]
I try to use it in livewire component but I have problem yet.

**Comment by ph7jack** [comment]
Same error?
What's your livewire version? Can show more details?

**Comment by aliqasemzadeh** [comment]
livewire component:
````
<?php

namespace App\Http\Livewire\Panel;

use Livewire\Component;

class Panel extends Component
{
    public $currency;

    public function render()
    {
        return view('livewire.panel');
    }
}
````

And view:
````
<x-panel-layout>
    <x-inputs.currency
        label="Currency"
        placeholder="Currency"
        thousands="."
        decimal=","
        precision="4"
        wire:model="currency"
    />
</x-panel-layout>

````

**Comment by ph7jack** [comment]
You can test this code?

```
<div x-data="{ name: @entangle('name') }">
     <span x-text="name"></span>
</div>
```

```
<php
...
public $name='testing';
...
```

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
Yet I get that error.
Please guide me to fix it.

**Comment by ph7jack** [comment]
@alighasemzadeh what's your livewire and laravel version?

**Comment by aliqasemzadeh** [comment]
Laravel 8.74.0
Livewire 2.5.1
@PH7-Jack

**Comment by ph7jack** [comment]
Can check if don't has any component that uses `@entangle` directive outside a livewire component?

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
How can I testit?

**Comment by ph7jack** [comment]
@alighasemzadeh you need to check in your base layout, check if has any blade component using `@entangle`

Check the route: if the route bind directly a livewire component https://laravel-livewire.com/docs/2.x/rendering-components#page-components
Check the blade app layout

You need to find a wrong importation of wireui component (that using @**entangle**) or any other component or code using this directive

You can try too clear view
`php artisan view:clear`

**Comment by aliqasemzadeh** [comment]
@PH7-Jack  
Fixed.
Just try to use full page component.
