### ISSUE TITLE
select Event don't work on multi select

### ISSUE THREAD

**Issue by trippo** [wireui/wireui#21]
**Describe the bug**
select Event doesn't work on x-select component
I tried only with multiselect options

**To Reproduce**
```
<x-select
   multiselect
    ...
    x-on:select="alert('selected/unselected option')"
>
    ...
</x-select>
```

**Additional context**
open and close event works fine

**Comment by ph7jack** [comment]
I tried here and I couldn't reproduce, this component is inside another alpine component?
Whats alpine version?

**Comment by trippo** [comment]
I tried now and work only selecting and not on unselecting

**Comment by ph7jack** [comment]
This has been fixed, check again with the latest version. If the issue has been resolved, close the issue

**Comment by trippo** [comment]
Now work fine. Thanks
