### ISSUE TITLE
Using Datetime Picker with Carbon model

### ISSUE THREAD

**Issue by trippo** [wireui/wireui#22]
Actually, the Datetime Picker component doesn't accept Carbon\Carbon type as livewire model, but it could be convenient on many occasions.

**Comment by ph7jack** [comment]
This is the error?
Cannot assign string to property App\Http\Livewire\Testing::$datetime of type ?Carbon\Carbon

**Comment by trippo** [comment]
Typed property App\Http\Livewire\Admin\Actions\CreateShopEntry::$dateTest must be an instance of Carbon\Carbon or null, string used

**Comment by ph7jack** [comment]
I'll think of a solution to do this treatment in livewire middleware, convert the string into an instance of carbon
This will be very useful

**Comment by trippo** [comment]
There is also another problem with dateTime component:
If you use a carbon date inside an eloquent for livewire model, you obtain an alpine error:
`Livewire Entangle Error: Livewire property 'shopEntry.entered_at' cannot be found`

But the value is setted on mount function like this:
`$this->shopEntry->entered_at = now()->roundMinute(10);`

I tried to format carbon with toIso8601String or others formats without success

**Comment by ph7jack** [comment]
You have a validation rule to binding directly to model property?

https://laravel-livewire.com/docs/2.x/properties#binding-models

**Comment by trippo** [comment]
You are right... there is not error with rule

**Comment by trippo** [comment]
There is another problem: I'm on Rome(UTC+2) timezone and if I pass "2021-06-16 19:50:00" to DateTime picker i see on the frontend 

16/06/2021 17:50

with these params
```
display-format="DD/MM/YYYY HH:mm"
parse-format="YYYY-MM-DD hh:mm:ss"
```
and with or without `without-timezone`

**Comment by ph7jack** [comment]
Can you give more information? I tried here and I couldn't reproduce

Your laravel timezone config is Europe/Rome?

Can you show me your component data using alpinejs tools? 
![image](https://user-images.githubusercontent.com/38913462/122430351-e840ab00-cf69-11eb-9568-dc5a8d282f0b.png)

**Comment by trippo** [comment]
There is also another little ui problem with time picker..
If you have a modal with blur like
<img width="878" alt="Schermata 2021-06-17 alle 09 37 54" src="https://user-images.githubusercontent.com/497169/122352956-deaa4980-cf4f-11eb-8c68-b125c16fb2f1.png">
and open a datetime picker
<img width="807" alt="Schermata 2021-06-17 alle 09 38 20" src="https://user-images.githubusercontent.com/497169/122353362-43fe3a80-cf50-11eb-841b-3818f01c1a29.png">
it create a space at the bottom of the page
<img width="811" alt="Schermata 2021-06-17 alle 09 38 31" src="https://user-images.githubusercontent.com/497169/122353434-54aeb080-cf50-11eb-853a-97fbff064b6e.png">

**Comment by trippo** [comment]
> Can you give more information? I tried here and I couldn't reproduce
> 
> Your laravel timezone config is Europe/Rome?
> 
> Can you show me your component data using alpinejs tools?
> ![image](https://user-images.githubusercontent.com/38913462/122430351-e840ab00-cf69-11eb-9568-dc5a8d282f0b.png)

![image](https://user-images.githubusercontent.com/497169/122909442-7bf0ed80-d355-11eb-9b8f-7efb66e58275.png)

**Comment by trippo** [comment]
> <img alt="Schermata 2021-06-17 alle 09 38 31" width="811" src="https://user-images.githubusercontent.com/497169/122353434-54aeb080-cf50-11eb-853a-97fbff064b6e.png">

This problem there is also with select (not native) on a modal when you open the select

**Comment by ph7jack** [comment]
The modal bug has been fixed

**Comment by ph7jack** [comment]
> There is another problem: I'm on Rome(UTC+2) timezone and if I pass "2021-06-16 19:50:00" to DateTime picker i see on the frontend
> 
> 16/06/2021 17:50
> 
> with these params
> 
> ```
> display-format="DD/MM/YYYY HH:mm"
> parse-format="YYYY-MM-DD hh:mm:ss"
> ```
> 
> and with or without `without-timezone`

If this still persists, create a new issue to this bug

**Comment by trippo** [comment]
Modal fixed.
Leave open for Carbon

**Comment by ph7jack** [comment]
@trippo 
The livewire community helped me find a solution to this.

https://github.com/livewire/livewire/discussions/3370

```
public function updatingDate(&$date)
{
    $date = Carbon::parse($date);
}
```

**Comment by trippo** [comment]
Work like a charme
