### ISSUE TITLE
Select option not filling in values properly from database

### ISSUE THREAD

**Issue by greenspace10** [wireui/wireui#23]
When loading a select from the database the data is stripped.

>
    <x-select label="Select Venue" placeholder="Select one status" wire:model.defer="editing.venue_id">
        @foreach ($venuesCol as $venue)
            <x-select.option label="{{ $venue->name }}" value="{{ $venue->id }}" />
        @endforeach
     </x-select>

![issue1](https://user-images.githubusercontent.com/55725358/122350750-7e011980-cf1b-11eb-829f-ba59b5807e9d.PNG)
![issue2](https://user-images.githubusercontent.com/55725358/122350775-835e6400-cf1b-11eb-912e-32c2024e3031.PNG)

**Comment by ph7jack** [comment]
Thanks for your report. Its is now fixed
Update to new version
If the issue has been resolved, close the issue. Thanks

I recommend don't use **"{{ }}"** to pass data to blade components
use ":" instead, laravel **"{{ }}"** encodes the value
https://laravel.com/docs/8.x/blade#html-entity-encoding

Ex: 
```
<x-select label="Select Venue" placeholder="Select one status" wire:model.defer="editing.venue_id">
    @foreach ($venuesCol as $venue)
        <x-select.option :label="$venue->name" :value="$venue->id" />
    @endforeach
 </x-select>
```

**Comment by greenspace10** [comment]
you know what that slipped my mind... awesome work!!!
