### ISSUE TITLE
select search reset

### ISSUE THREAD

**Issue by greenspace10** [wireui/wireui#24]
**Describe the bug**
when using select with search on a livewire component, search box does not clear until page is refreshed.

**To Reproduce**
use any select with search

**Additional context**
Recommend either:
1. add search: '' to closePopover()

>     closePopover() {        
>         this.popover = false
>         search: ''
>         this.$refs.select.dispatchEvent(new Event('close')) 
>     },

2. watch for a emit('clear') from livewire.

nonetheless Great work! I have used a number of the available components, with little to no issues. although bit more documentation on some of them would be beneficial!

**Comment by ph7jack** [comment]
Maybe be more convenient to clear search when select/unselect option.

**Comment by ph7jack** [comment]
Thanks for your report

**Comment by ph7jack** [comment]
It is now fixed
