### ISSUE TITLE
Position of modal in mobile

### ISSUE THREAD

**Issue by aliqasemzadeh** [wireui/wireui#26]
![Screenshot_20210621-105554_Chrome.jpg](https://user-images.githubusercontent.com/26847446/122716716-772a1d80-d21f-11eb-8ba6-42e146242d2e.jpg)

Please see modal.
I think margin top need to be change.

**Comment by ph7jack** [comment]
Thanks for reporting this. I will find a way to solve this viewport problem

**Comment by ph7jack** [comment]
If scroll down, the button show up?

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
Yes with scroll I can see buttons.

**Comment by ph7jack** [comment]
It is now fixed, check again using latest version

**Comment by ph7jack** [comment]
Closing, if the bug persists, comment to reopen
