### ISSUE TITLE
Date picker and timezone

### ISSUE THREAD

**Issue by trippo** [wireui/wireui#32]
There is another problem: I'm in Rome(UTC+2) timezone and if I pass "2021-06-16 19:50:00" to DateTime picker I see on the frontend

16/06/2021 17:50

with these params

display-format="DD/MM/YYYY HH:mm"
parse-format="YYYY-MM-DD hh:mm:ss"
and with or without without-timezone

![122909442-7bf0ed80-d355-11eb-9b8f-7efb66e58275](https://user-images.githubusercontent.com/497169/123386622-2441c480-d597-11eb-851e-3e6733dbb2f0.png)

**Comment by ph7jack** [comment]
Can check it again?
What's your alpine version?

**Comment by trippo** [comment]
Alpine: 3.2.1
I think because the field is cast to a Carbon
I think when you implement carbon type this issue will be resolve

**Comment by diazsasak** [comment]
@trippo i got the same bug. how you resolve the issue?

**Comment by visoftdev** [comment]
> @trippo i got the same bug. how you resolve the issue?

use timezone="UTC" in datetime picker

**Comment by visoftdev** [comment]
> @trippo i got the same bug. how you resolve the issue?

use timezone="UTC" in datetime picker and Carbon::parse($value)->timezone(Config::get('app.timezone'));

**Comment by ph7jack** [comment]
@diazsasak @visoftdev pass the user-timezone and the system timezone
`<x-datetime-picker :timezone="$timezone" :user-timezone="$userTimezone" ... />`

The user timezone is the navigator timezone by default
The System Timezone is UTC by default

**Comment by visoftdev** [comment]
> 

I use in blade: 

`<x-datetime-picker label="Thời gian" timezone="UTC" time-format=24 interval=30 class="my-2"
        placeholder="Chọn thời gian" wire:model="datetime" />`

in component:

$date = Carbon::parse($this->datetime)->timezone(Config::get('app.timezone'));

It worked!

Thanks

**Comment by trippo** [comment]
I used  timezone="UTC" user-timezone="UTC" and carbon with default config ('Europe/Rome')

**Comment by baoanhng** [comment]
Why close, this hasn't been resolved. The problem is we have to manually adjust the timezone instead of using what Carbon has already provided.
