### ISSUE TITLE
Method Component::notify does not exist.

### ISSUE THREAD

**Issue by bernhardh** [wireui/wireui#33]
**Describe the bug**

The documented function

```php
// or use a full syntax
$this->notify([
    'title'       => 'Profile saved!',
    'description' => 'Your profile was successfull saved',
    'icon'        => 'success'
]);
```

doesn't work. This method does not exist in the `WireUi\Traits\Actions` trait.

**Comment by ph7jack** [comment]
Thanks for reporting this

I forgot of update this example
Notifications api has recently changed

use `$this->notification()->notify([...])` instead

I'm thinking in new methods to show notifications, like

```
$this->notification([...]) // maybe be nice
$this->notification()->success(...) // this exists
```
