### ISSUE TITLE
Notifications aren't working

### ISSUE THREAD

**Issue by bernhardh** [wireui/wireui#34]
**Describe the bug**
I try to use the notification component. I added the `<x-notifications />` into my layout on the first line after the body open tag. In my LiveWire Component I added the `Actions` trait and then called the example code into a form submit method (which is also sending an email, which I get so the method is called): 

```php
$this->notification()->success(
    $title = 'Profile saved',
    $description = 'Your profile was successfull saved'
);
```
and this is the result I get in network tab:

![image](https://user-images.githubusercontent.com/642292/123400853-7b02ca80-d5a6-11eb-99a5-ce99e62ee8b7.png)

but no notification is shown. 

To test it further, I created a simple blade view:

```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @livewireStyles
    @wireUiScripts
</head>
<body>
<x-notifications />
<x-dialog z-index="z-50" blur="md" align="center" />
@livewireScripts
</body>
</html>
```

and then called the notification over the browser console:

```js
window.$wireui.notify({
    title: 'Profile saved!',
    description: 'Your profile was successfull saved',
    icon: 'success'
})
```

Same. Nothing happens. The same problem occurs with the dialog.

In all cases - no error message or something is shown in the brower console.

**Comment by ph7jack** [comment]
Are you importing alpinejs in this layout?

**Comment by bernhardh** [comment]
Well. No. That was the problem. Thank you very much.

**Comment by henryejemuta** [comment]
I'm currently having issues getting notifications and dialog to work, I keep getting the error below:
```
   VM6166:8 Uncaught SyntaxError: missing ) after argument list
    at new Function (<anonymous>)
    at Directive.value (wire-directives.js:93)
    at Directive.get (wire-directives.js:58)
    at node_initializer.js:207
    at Component.value (index.js:584)
    at HTMLAnchorElement.<anonymous> (node_initializer.js:199)
```

AlpineJs is currently imported via the `js/app.js` below is the sample of my layout blade file

```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   
    <livewire:styles/>
    <wireui:scripts/>

    <script src="{{ url(mix('js/app.js')) }}" defer></script>
</head>
<body>
<x-dialog  z-index="z-50" />
<x-notifications z-index="z-50" />
        <main >
                @yield('body')
        </main>
<livewire:scripts/>
</body>
</html>
```

within my Livewire component, I tried using either the `dialog` with
```
      $this->dialog()->success(
            'Business Deactivated!',
            "$name has been successfully deactivated."
        );
```
also tried `notification` with
```
      $this->notification()->success(
            'Business Deactivated!',
            "$name has been successfully deactivated."
        );
```

but keep getting the same error as highlighted earlier, modal and other components work fine
