### ISSUE TITLE
Seelect dislay value and lable both in has error

### ISSUE THREAD

**Issue by gps-dev-team** [wireui/wireui#340]
**Describe the bug**
Jumbled data displayed on select when if has validation error. 

**To Reproduce**
1. select select
 ```
<x-select
                wire:model="customer_id"
                label="Status"
                placeholder="Select one status"
                serachable="false"
                :options="[
                    ['name' => 'Active',  'id' => 1],
                    ['name' => 'Pending', 'id' => 2],
                    ['name' => 'Stuck',   'id' => 3],
                    ['name' => 'Done',    'id' => 4],
                ]"
                option-label="name"
                option-value="id"
            />
```
3. select a value
4. create validation error
5. page reloaded with errors and jumbled characters

**Expected behavior**
Just a label as
**Screenshots**
`normal:`
<img width="827" alt="image" src="https://user-images.githubusercontent.com/104731786/175350267-2bacdd03-ed18-4f50-aebe-e162a7a2225d.png">
`with Error:`
<img width="864" alt="image" src="https://user-images.githubusercontent.com/104731786/175351155-cb2ff16f-f197-41b0-b463-bfae84d9cb97.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
PHP: 8.0
Laravel: 9.12
Livewire version: 2.10.5
WireUI version: 1.5.0

**Comment by joelhmetz** [comment]
Add
`.text-transparent { color: transparent !important; }`

**Comment by gps-dev-team** [comment]
Thanks it Solve the problem
