### ISSUE TITLE
Feature: Input with buttons

### ISSUE THREAD

**Issue by bernhardh** [wireui/wireui#35]
An option to attach an button to an input like this:

![image](https://user-images.githubusercontent.com/642292/123404003-2f055500-d5a9-11eb-8546-4dafa8803159.png)

Or this:

(https://tailwindcomponents.com/component/search-input-with-integrated-icon-and-button)

**Comment by ph7jack** [comment]
You can use prepend and append slots to do it
https://livewire-wireui.com/docs/inputs#input-append

In soon, with customizable colors, and customizable input rounded, squared, filled... it will be better

![image](https://user-images.githubusercontent.com/38913462/123430879-0e380200-d59f-11eb-8975-d193441f1165.png)
```
<x-input label="Email">
    <x-slot name="prepend">
        <div class="absolute right-0 top-0 inset-y-0">
            <x-button label="Submit"  primary class="h-full rounded-l-none" />
        </div>
    </x-slot>
</x-input>
```
