### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by aliqasemzadeh** [wireui/wireui#36]
Hi
I change my website to force SSL
now I get:
Mixed content: load all resources via HTTPS to improve the security of your site
Even though the initial HTML page is loaded over a secure HTTPS connection, some resources like images, stylesheets or scripts are being accessed over an insecure HTTP connection. Usage of insecure resources is restricted to strengthen the security of your entire site.
To resolve this issue, load all resources over a secure HTTPS connection.

How can I force SSL for WireUI.

**Comment by jan-edge** [comment]
How do you force resources to load over https? APP_URL in .env is https, and `\URL::forceScheme('https');` is applied in the AppServiceProvider, but the page source still shows http in the script src for @wireUiScripts .
`route('wireui.assets.scripts')` outputs the https url, while `@wireUiScripts` still uses http in src. All caches have already been cleared.

**Comment by ph7jack** [comment]
@jan-edge If your server is sending over SSL, the laravel automatically will add the HTTPS to wireui routes.
Try to clear the routes and the views
```
php artisan optimize:clear
php artisan view:clear
php artisan route:clear
```

**Comment by jan-edge** [comment]
Thanks for the quick reply.
All pages are already served over ssl and clearing all these caches didn't have any effect.
Only a composer reinstall did the trick.
