### ISSUE TITLE
Accept key value array as Select Options

### ISSUE THREAD

**Issue by trippo** [wireui/wireui#45]
I would like to have the possibility to pass an key value array as options params on select like this
```php
[ 
   1 => "name1" ,
   2 => "name2" ,
]
```
So without 
```
option-label="name"
option-value="id" 
```

**Comment by ph7jack** [comment]
Maybe **option-key-label** **option-key-value** as boolean prop

What do you think about this?

**Comment by trippo** [comment]
I think is better if the default (without passing option-label and option-value) work with an key value arrya.
If you specify option-label and option-value work like now.

**Comment by ph7jack** [comment]
You talk about defaulting to key as value?
```
$array = [ 
   1 => "name1" ,
   2 => "name2" ,
];
```

the value is **1** and **2**, the label is **name1** and **name2**

**Comment by trippo** [comment]
Yes

**Comment by ph7jack** [comment]
It will break if pass an array of values, like `$array = ['Active', 'Pending', 'Stuck', 'Done']`, the value will be 0,1,2... and not Active, Pending...

**Comment by ph7jack** [comment]
I believe a prop to define this would be good

**Comment by trippo** [comment]
You are the magician :) 
what did you think about option-key-label option-key-value as boolean prop?

**Comment by ph7jack** [comment]
I believe it can be a way, I am open to suggestions. I'm still thinking about it

**Comment by ph7jack** [comment]
@trippo it is now released

You can use **option-key-label** or **option-key-value**

**Comment by trippo** [comment]
Work like a charme
