### ISSUE TITLE
Unable to locate a class or view for component [error]

### ISSUE THREAD

**Issue by trippo** [wireui/wireui#5]
**Describe the bug**
When I try to use x-error component obtain this error:
`Unable to locate a class or view for component [error]`
If I use 
`@error('model') <span class="text-red-600">{{ $message }}</span> @enderror`
or add the error component on resource > views > components
All work fine

**To Reproduce**
1. Include x-error component on a livewire component

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser chrome
 - Version 90

**Additional context**
If I publish the wireui components with command `php artisan vendor:publish --tag='wireui.resources'` not work

**Comment by ph7jack** [comment]
This is resolved now, closing issue
