### ISSUE TITLE
Option to enable/disable (and maybe rename) blade components.

### ISSUE THREAD

**Issue by Reex11** [wireui/wireui#52]
**Related Problem**
I'm using another packages that uses "icon","text","textarea","label","button","dropdown" blade component name and wireUI is conflicting with it.
To be more clear, I'm only planning to use the the following components from this package:

- Datetimepicker
- Notifications
- Toggle
- Checkbox

**The solution I'd like**
It would be nice to disable the other components as I'll not be using them. & to avoid any conflicts if the same name is used.

**Alternatives solutions**
- the ablility to rename these components to avoid conflict if I'm planning to use both packages.

**Comment by ph7jack** [comment]
It is now finished. I'm working on documentation for this, and release the feature.
@itepifanio thanks for the contribution
