### ISSUE TITLE
Datetime picker dissapears on navigation click

### ISSUE THREAD

**Issue by Quintenps** [wireui/wireui#56]
**Describe the bug**
Whenever navigating through the dates in the datetime picker component, it auto closes.

**To Reproduce**
1. Open the datetime picker
2. Click anywhere

**Expected behavior**
Just like the demo page here, it should be able to navigate through the dates.

**Screenshots**

https://user-images.githubusercontent.com/8738094/128228916-bfefabcf-aed6-4ed6-b2bf-fd862d7c4e79.mp4

`<x-datetime-picker
                            without-time
                            label="Birthday"
                            display-format="DD-MM-YYYY"
                            parse-format="YYYY-MM-DD"
                            wire:model="personalCard.birthday"
                        />`

It's also worth noting that it also has the same behaviour when no attributes are defined. i.e `<x-datetime-picker />`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome (Version 92.0.4515.131 (Official Build) (64-bit))

**Additional context**
I'm using AlpineJS version 2.8.2. 

Thank you for this awesome package <3

**Comment by ph7jack** [comment]
Hello @Quintenps, thanks for your report
This package is not fully compatible with alpine v2.x
Can you use alpine v3?

**Comment by Quintenps** [comment]
Thanks for the quick response. 
Oh I tried checking package requirements but didn't see them anywhere.

Just wanted to make sure it wasn't something stupid on my end.
Issue can be closed :)

**Comment by ph7jack** [comment]
Is very simple to update to v3
https://alpinejs.dev/upgrade-guide
