### ISSUE TITLE
prepend and append view problem

### ISSUE THREAD

**Issue by aliqasemzadeh** [wireui/wireui#58]
https://github.com/alighasemzadeh/dolist/blob/64a827b1f30b17018875dc910c35e310a8258fe0/resources/views/livewire/task/edit.blade.php#L5

Hi I have one input with both prepend and append.
1-Display is not right.
2-Buttons not work.

my demo application is : dolist.ir

**Comment by ph7jack** [comment]
Hello @alighasemzadeh 

We can fix your button style using it
Note: The left and right padding is not added by default, you must set it in input classes
```
<x-input class="pl-12">
    <x-slot name="prepend">
        <div class="absolute inset-y-0 left-0 flex items-center p-0.5">
            <x-button
                class="rounded-l-md h-full"
                icon="minus"
                primary
                flat
                squared
            />
        </div>
    </x-slot>

    <x-slot name="append">
        <div class="absolute inset-y-0 right-0 flex items-center p-0.5">
            <x-button
                class="rounded-r-md h-full"
                icon="plus"
                primary
                flat
                squared
            />
        </div>
    </x-slot>
</x-input>
```
![2021-08-11_10-50](https://user-images.githubusercontent.com/38913462/129041161-34665eef-0ef2-4989-91f6-553267ad6e0c.png)


I found an error in your input, you are using `wire:modal` instead `wire:model`
https://github.com/alighasemzadeh/dolist/blob/64a827b1f30b17018875dc910c35e310a8258fe0/resources/views/livewire/task/edit.blade.php#L5

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
Hi
This is what I see:
![1](https://user-images.githubusercontent.com/26847446/129175380-653a4c39-011c-49f0-b010-294a089e6306.jpg)

**Comment by ph7jack** [comment]
You need to add padding-left in your input

`  <x-input class="pl-10" label="{{ __('dolist.duration') }}" placeholder="{{ __('dolist.duration') }}" wire:modal="duration">`

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
I rebuild assets and it fixed.
