### ISSUE TITLE
Possibility to change colors/class

### ISSUE THREAD

**Issue by paddy01** [wireui/wireui#59]
**Is your feature request related to a problem? Please describe.**
No, it would just be nice

**Describe the solution you'd like**
Best would be to be able to override current class with your own, that way it can be heavily modified without you having to modify the code to much!

**Describe alternatives you've considered**
I primarily try to use the toggle function and the color scheme is just wrong in my application. I already have a different variation but it is not as neat as yours!

**Additional context**

***Note:***
Very nice job on this add-on, it melts beautifully into my already setup application without to much fuzz :)

**Comment by ph7jack** [comment]
Hello @paddy01 , thanks for appreciating this package
Can you give me an example for it?

Now, is only possible to customize the components colors

**Comment by paddy01** [comment]
![image](https://user-images.githubusercontent.com/2136198/129201908-c89b86af-43d0-412d-88b8-daa83bb8c1d4.png)
Left being what it is today and right what I'd like to achieve.
I know this is very crude ( done in paint! *shiver* )but I think you understand the basic idea ?
a.k.a. I'd like to modify the (un)checked colors on the specific toggle - not all of them - and also if possible the font settings used in the label.

**Comment by ph7jack** [comment]
Ok, i understood now. In soon I  will give more information about that. I'm refactoring all components to add more browsers support.

**Comment by lucasantonioedmond** [comment]
The colors we got by changing the tailwindcss config.

But the main problem we have is in switching classes.

We tried creating a custom blade component and cleared the cache.

This whole process didn't work.

**Comment by REJack** [comment]
May you need to run `artisan optimize:clear`, that helped me a alot with changing classes in wireui components.

**Comment by ph7jack** [comment]
@paddy01 I'm now closing this issue, the wireui will not provide this customization out of the box, if you need it, publish the resources and make the changes. Thanks for using the WireUI
