### ISSUE TITLE
Not executing accept/reject action

### ISSUE THREAD

**Issue by pndjike** [wireui/wireui#66]
Hello,

I have an issue with the package. I have this code inside the Blade of a Livewire Component.

![image](https://user-images.githubusercontent.com/87007602/130369755-55935c7b-2546-442a-ae98-f1394ecc2e6b.png)

The notification displays well.

![image](https://user-images.githubusercontent.com/87007602/130369945-745fb43a-c666-406e-b846-70b2bf2bee51.png)

But, when I click on the accept or reject button, nothing happens. The modal just closes and it's not triggering the code in the Livewire class.

 - OS: Windows
 - Browser: Edge
 - Package version: 0.11.4
 - Laravel 8
 - PHP 8

**Comment by ph7jack** [comment]
Hello @pndjike 
When you are using the confirmNotification method to create a new notification, you need to pass the livewire ID in the second parameter. Or, use the `x-on:confirm`, the livewire id will be automatic, I recommend this instead
```
x-on:confirm="{
        title: 'Are you Sure?',
        description: 'Save the information?',
        icon: 'question',
        accept: {
            label: 'Yes, save it',
            method: 'save',
            params: 'Saved'
        },
        reject: {
            label: 'No, cancel',
            method: 'cancel'
        }
    }"
```

If you will use it this way, pass the component id
```
onclick="window.$wireui.confirmNotification({
        title: 'Are you Sure?',
        description: 'Save the information?',
        icon: 'question',
        accept: {
            label: 'Yes, save it',
            method: 'save',
            params: 'Saved'
        },
        reject: {
            label: 'No, cancel',
            method: 'cancel'
        }
    }, '{{ $this->id }}')"
```

**Comment by pndjike** [comment]
Thanks, it solved the problem!!!
