### ISSUE TITLE
Notifications: Missing semicolon

### ISSUE THREAD

**Issue by tmdevde** [wireui/wireui#67]
**Describe the bug**
I'm trying to implement notifications but when the page is loaded I get an error message in the console:
`Uncaught SyntaxError: Unexpected token 'if'`

It's referencing the Notification Template (published in the configs) at line 7:
`notification.id = $wireui.utils.uuid()`

When I add a semicolon at the end of the line the error just moves to the next one and so on.
Other Components like Dropdown are working fine. I think the error is properly with my environment.
I don't use Typescript just plain TALL Stack.

**To Reproduce**
1. See [Notifications](https://livewire-wireui.com/docs/notifications)

**Expected behavior**
Showing notifications

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version; latest

Any help would be appreciated.

**Comment by tmdevde** [comment]
Solved it by myself. There was a problem with  [Laravel Page Speed](https://github.com/renatomarinho/laravel-page-speed). As I disabled it the error was gone.

**Comment by ph7jack** [comment]
Hello @tmdevde 

This error is not in your environment. Nobody needs to use typescript to use this package, the ts code is compiled to js.
It's broken because the [Laravel Page Speed](https://github.com/renatomarinho/laravel-page-speed) package remove all line break in all rendered blade, and ignore the js code inside alpinejs.

**Comment by tmdevde** [comment]
Yes figured this out too. Thank you for answering. Awesome Library btw ;-). You can delete this issue or let it stay if anyone is as foolish as me and searching for a solution.

**Comment by ph7jack** [comment]
Closing issue
