### ISSUE TITLE
Collision with my current notification system

### ISSUE THREAD

**Issue by labomatik** [wireui/wireui#70]
**Describe the bug**
After the composer install, i've an error linked to my own notification system:
```Attempt to read property "id" on null ```

**To Reproduce**
My notification system is base on the one from Caleb described in Livewire here https://laravel-livewire.com/screencasts/s8-toasters

part of the code is  in the notification.blade.php
```
<div x-data="{
        messages: [],
        remove(message) {
            this.messages.splice(this.messages.indexOf(message), 1)
        },
        autoclose: true,
    }" @notify.window="let message = $event.detail.message; messages.push(message); autoclose = $event.detail.autoclose; if(autoclose){ setTimeout(() => { remove(message) }, 5000) }" class="fixed inset-0 flex flex-col items-end justify-center px-4 py
 
 
 
 
</div>

```
**Expected behavior**
Should not cause any issue.

**Desktop (please complete the following information):**
Alpine V2

**Comment by ph7jack** [comment]
Hello @labomatik 
Can you rename your notification component?
Can give more details about this error?

**Comment by labomatik** [comment]
Hello @PH7-Jack 
I just renamed the component to messageNotification without any success

here is more error info:
```
Attempt to read property "id" on null (View: /resources/views/components/messageNotification.blade.php)
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
resources/views/components/messageNotification.blade.php:7
```

Removing my component inside the main layout is working (but not the solution :-) )

![image](https://user-images.githubusercontent.com/179987/131239793-1c8bb621-6773-44a2-b248-5c59a481e4f2.png)

**Comment by labomatik** [comment]
I just modified the complete notify method (replace @notify by @toasterNotify) and all is fine :-)
there was a collision with the notify listener in alpine.
