### ISSUE TITLE
Closing the Time select is submitting a normal form

### ISSUE THREAD

**Issue by labomatik** [wireui/wireui#72]
If you place the time picker inside a normal `<form></form>` closing the time picker select is submitting the form (it is acting as a normal button)
https://github.com/PH7-Jack/wireui/blob/d197de88449825041e0df38e1a65ac53573fc491/resources/views/components/time-picker.blade.php#L267
should be modified to include this tag (html5)
```
 type="button"
```

**Comment by ph7jack** [comment]
Thanks for reporting this. I will fix it today.

**Comment by ph7jack** [comment]
It is now fixed, if the error happens again comment to reopen
