### ISSUE TITLE
Jalali datepicker

### ISSUE THREAD

**Issue by aliqasemzadeh** [wireui/wireui#76]
I want to have jalali datepicker I find out you use dayjs for datepicker.
We have dayjs-jalali how can I use it for datepicker?
https://www.npmjs.com/package/dayjs-jalali

**Comment by ph7jack** [comment]
Hello @alighasemzadeh 

I will create an integration for it

**Comment by ph7jack** [comment]
In now is not possible to use without rebuild assets manually

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
Guide me t do it.

**Comment by ph7jack** [comment]
For now, the unique way to do it is by creating a fork

Add a new line to extends dayjs-jalali
https://github.com/PH7-Jack/wireui/blob/master/ts/utils/date.ts#L9

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
I want to have jalali datepicker  something like :
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/

Is it possible with that replacement?

**Comment by ph7jack** [comment]
In the published view file, you can translate all names of days, months...

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
My Test: https://noyan.cloud/test   Repo: https://github.com/alighasemzadeh/noyan.cloud
My Package:https://github.com/alighasemzadeh/wireui

I rebuild all assets but it doesn't work.
Where should I add ` { jalali: true }`

**Comment by ph7jack** [comment]
I don't know how to add Jalali, but I will search for it

**Comment by aliqasemzadeh** [comment]
I did it.
Just I have some problem:
1-Year not pass when click on date. (This might be problem of datepicker)
2-Set first day of week is important

**Comment by ph7jack** [comment]
I will have news about this soon. At the moment it is not possible

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
https://github.com/zoomit-org/Dayjs-Jalali-Plugin
I found new jallali date for Persian language.

````
import jalaliPlugin from '@zoomit/dayjs-jalali-plugin'

dayjs.extend(jalaliPlugin)
dayjs.extend(utc)
dayjs.extend(timezone)
dayjs.extend(customParseFormat)
dayjs.extend(localizedFormat)
dayjs.calendar('jalali')
````

It display wrong dates.

**Comment by haidarhalessa** [comment]
Hello @PH7-Jack 

Thanks for this amazing package.
Can you add **Hijri calendar** as well in the datepicker input? :)

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
Any news about Jalali datepicker?

**Comment by ph7jack** [comment]
@alighasemzadeh for now, i don't have any news, sorry

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
Any news about using Jalali?

**Comment by ph7jack** [comment]
@alighasemzadeh Unfortunately no, I'm planning it to the new release 2.x with the RTL support

**Comment by joaopalopes24** [comment]
There are no plans to implement this solution. We are updating the status of the Issues and if you want to contribute to this solution, it's welcome.

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
@joaopalopes24 
https://github.com/shalior/filament-persian-date-field


Hi I think we can add this field to wireui.
