### ISSUE TITLE
JavaScript Notification

### ISSUE THREAD

**Issue by NenadGajic** [wireui/wireui#8]
**Describe the bug**
When trying to show Notification component with JavaScript following the steps and description from documentation, it doesn't work.

`console.log(window.$wireui)` shows "undefined"

**To Reproduce**
1. Fresh install Laravel & Livewire + Wireui
2. Include **<x-notifications />** to layout file
3. Below `@wireUiScripts` add 
```
<script>    
      window.$wireui.notify({
          title: 'Profile saved!',
          description: 'Your profile was successfull saved',
          icon: 'success'
      })
</script>
```
(docs example)

**Expected behavior**
Success notification is shown :)

Showing notifications from Livewire component using $this->notify() or $this->successNotification() works as expected.

**Comment by ph7jack** [comment]
Hello @NenadGajic, thanks for reporting this

The WireUi scripts will be available after script is load on page.
I will add **wireui:load** event to inform when wireui is loaded.

For now, you can use **livewire:load** event
`document.addEventListener("livewire:load", () => console.log(window.$wireui))`

**Comment by NenadGajic** [comment]
I totally forgot about livewire:load event, thanks!
It loads now the object correctly in the console, but still for some reason it doesn't show the notification when using the example from the documentation.

```
window.$wireui.notify({
    title: 'Profile saved!',
    description: 'Your profile was successfull saved',
    icon: 'success'
})
```

However, when I try to call the function from a click event on a button, it works fine.

```
<button onclick="window.$wireui.notify({
          title: 'Profile saved!',
          description: 'Your profile was successfull saved',
          icon: 'success'
})">Notification Test</button>
```

Is this normal behavior?

btw, I'm trying to use the notification component when flashing the data into session and redirecting. My idea was to add `@if (session()->has('xy')` to the layout and then display JS script tag that calls the notify function if there is data in the session.
Is there any better way to achieve this?

Thanks and also thanks for this great and useful package. 😃

**Comment by ph7jack** [comment]
The Notifications component is initialized with alpinejs, then need wait it loaded
This is normal behavior 
I published a new release with [WireUi Hooks](https://livewire-wireui.com/docs/hooks) 

Use it to show notification on page load
```
@if (session()->has('xy'))
    Wireui.hook('notifications:load', () => {
        window.$wireui.notify({
            title: 'Profile saved!',
            description: 'Your profile was successfull saved',
            icon: 'success'
        })
    })
@endif
```
Thanks for using WireUi ❤️

**Comment by NenadGajic** [comment]
That's it! Awesome, thanks for the quick solution, works great, as expected!

I will close the issue.
