### ISSUE TITLE
Ability to compile javascript with everything else

### ISSUE THREAD

**Issue by vlados** [wireui/wireui#88]
This will help for two reasons:
- make one request less to the server to load the javascript. Now the request to javascript is going thru the php making it slower. If the request is directly to the javascript as static file will be faster for sure.
- ~~ability to change the classes of the dialog~~ This can be archived with **iconBackground**
```js
  window.$wireui.dialog({
      title: 'Profile saved!',
      description: 'Your profile was successfull saved',
      icon: 'success',
      iconBackground:'p-2 bg-positive-50 dark:bg-secondary-700 border dark:border-0 rounded-3xl'
  })
```

**Comment by ph7jack** [comment]
If you publish the resources is possible to change anything, but you need to install ts compiler in your project. See about laravel mix ts https://laravel-mix.com/docs/6.0/api#tssrc-dist

About the js request: all wireui requests are cached in the browser, so, the user makes the assets request one time, and get it in cache.
I'll think about the assets compilation inside the project

**Comment by vlados** [comment]
For future reference, this is how you can compile scripts and include the js in the html (@PH7-Jack, maybe you can include it in the documentation):
webpack.mix.js
```js
mix.ts('./vendor/ph7jack/wireui/ts/index.ts', './public/js/wireui.js');
```

html head
```html
<script>window.Wireui = {hook(hook, callback) {window.addEventListener(`wireui:${hook}`, () => callback())},dispatchHook(hook) {window.dispatchEvent(new Event(`wireui:${hook}`))}}</script>
<script src="{{ url(mix('js/wireui.js')) }}"></script>
```

**Comment by vlados** [comment]
With Vitejs:
```blade
    <script>
        window.Wireui = {
            hook(hook, callback) {
                window.addEventListener(`wireui:${hook}`, () => callback())
            },
            dispatchHook(hook) {
                window.dispatchEvent(new Event(`wireui:${hook}`))
            }
        }
    </script>
    <script src="{{ Vite::asset('vendor/wireui/wireui/dist/wireui.js') }}" defer></script>
```
